### PR TITLE
Transform cartesian commands into model frame

### PR DESCRIPTION
**Pull request by 2scholz**
Previously it was assumed that the incomming cartesian commands were already in the model frame.
Now, the incoming cartesian commands are transformed from the given frame into the model frame.

### CODE REVIEW

**Comment by v4hn** [comment]
why did you close #1 #2 #3 without feedback?

**Comment by davetcoleman** [comment]
This is disconcerting to say, but I have no idea why this was closed or how I force-pushed this repo. Was this somehow auto-tiggered by Github?

**Comment by v4hn** [comment]
I have absolutely no idea.
This is your repository.
I would expect only you can change things here unless you explicitly invited other developers.

**Comment by davetcoleman** [comment]
Unfortunately the reopen button is disabled, sorry @2scholz do you still have your requested changes somewhere? Can you re-open the PR?

**Pull request closed without merging**
